apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment 
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: devops-project  
  template:
    metadata:
      labels:
        app: devops-project  
    spec:
      containers:
      - name: devops-project  
        image: giyordanov/devops-project:latest 
        ports:
        - containerPort: 5000

