apiVersion: v1
kind: Service
metadata:
  name: devops-project-main-service
spec:
  selector:
    app: devops-project  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  
      nodePort: 30001 
  type: NodePort
