name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:  
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Run flake8 for code style check
        uses: py-actions/flake8@v2

  editorconfig-check:
    name: EditorConfig check
    runs-on: ubuntu-latest
    needs: flake8-check 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

  unit-testing:
    runs-on: ubuntu-latest
    needs: [flake8-check, editorconfig-check]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Run tests
        run: python -m unittest src/app_test.py

  docker-build-and-scan:
    runs-on: ubuntu-latest
    needs: [unit-testing]
    permissions:
      security-events: write
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t giyordanov/devops-project:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: giyordanov/devops-project:latest
          format: 'sarif'  
          output: 'trivy-results.sarif' 
          exit-code: 0  
          ignore-unfixed: true 
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'  
          sha: ${{ github.sha }} 
          ref: ${{ github.ref }}