name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:  
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'
      - name: Upgrade Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run flake8 for code style check
        run: |
          flake8 src --max-line-length=100

  unit-testing:
    runs-on: ubuntu-latest
    needs: flake8-check 
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run tests
        run: |
          python -m unittest src/app_test.py

